name: Queue Service Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        cd ./queue-service
        docker build . --file send/Dockerfile --tag ${DOCKER_USER}/taxareceive:taxa-publisher
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push ${DOCKER_USER}/taxareceive:taxa-publisher
      
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        cd ./queue-service
        docker build . --file bookinghandlerservice/Dockerfile --tag ${DOCKER_USER}/taxareceive:handler-svc
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push ${DOCKER_USER}/taxareceive:handler-svc
